import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDatabase } from '../context/DatabaseContext';
import { supabase } from '../lib/supabase';
import { toast } from 'react-hot-toast';

export function AdminAddProductPage() {
  const { addProduct } = useDatabase();
  const navigate = useNavigate();

  // Controlled form states
  const [name, setName] = useState('');
  const [price, setPrice] = useState('');
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    
    // Basic validation to check if all inputs including file are present
    if (!name || !price || !imageFile) {
      toast.error('Please fill in all fields and select an image file.');
      return;
    }

    setIsSubmitting(true);

    try {
      // 1. Generate a completely unique file name using timestamp and random number
      const fileExtension = imageFile.name.split('.').pop();
      const uniqueFileName = `${Date.now()}-${Math.floor(Math.random() * 1000)}.${fileExtension}`;
      const filePath = `shoes/${uniqueFileName}`;

      // 2. Upload the raw binary file directly to Supabase Storage Bucket
      const { error: uploadError } = await supabase.storage
        .from('product-images')
        .upload(filePath, imageFile, {
          cacheControl: '3600',
          upsert: false
        });

      if (uploadError) throw uploadError;

      // 3. Retrieve the persistent public URL generated by Supabase for this uploaded asset
      const { data: { publicUrl } } = supabase.storage
        .from('product-images')
        .getPublicUrl(filePath);

      // 4. Pass the newly retrieved cloud image URL into our main database product creator
      await addProduct(name, Number(price), publicUrl);
      
      toast.success('Product added successfully with real cloud storage image!');
      navigate('/');
    } catch (error: any) {
      console.error('Error uploading image or adding product:', error.message);
      toast.error(`Failed to save product: ${error.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="max-w-md mx-auto">
      <h2 className="text-xl font-bold text-gray-800 mb-6">Management: Add New Product</h2>
      
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Product Name</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="e.g., Nike Air Max 90"
            required
            className="w-full border border-gray-300 rounded-md p-2 text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Price (₽)</label>
          <input
            type="number"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
            placeholder="e.g., 15990"
            required
            className="w-full border border-gray-300 rounded-md p-2 text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Product Photo</label>
          <input
            type="file"
            accept="image/*"
            required
            onChange={(e) => {
              if (e.target.files && e.target.files[0]) {
                setImageFile(e.target.files[0]);
              }
            }}
            className="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 cursor-pointer"
          />
        </div>

        <div className="pt-2 flex gap-3">
          <button
            type="button"
            onClick={() => navigate('/')}
            className="w-1/2 border border-gray-300 hover:bg-gray-50 text-gray-700 font-medium py-2.5 rounded-md text-sm transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-1/2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-bold py-2.5 rounded-md text-sm transition-colors shadow-sm"
          >
            {isSubmitting ? 'Uploading...' : 'Save Product'}
          </button>
        </div>
      </form>
    </div>
  );
}